server:
  disable: true
clients:
  - url: http://127.0.0.1:3100/api/prom/push
positions:
  filename: "/run/promtail/positions.yaml"
scrape_configs:
- job_name: insights
  static_configs:
  - targets:
    - localhost
    labels:
      __path__: /tmp/log/diffs.log
  pipeline_stages:
  - json:
      expressions:
        diff: diff
        file: file
        snapshot: snapshot
        operation: operation
        field: field
  - labels:
        file: file
        snapshot: snapshot
        operation: operation
        field: field
  - output:
      source: diff
