clients:
  - url: http://192.168.1.162:3100/api/prom/push
positions:
  filename: "/run/promtail/positions.yaml"
scrape_configs:
- job_name: insights
  static_configs:
  - targets:
    - localhost
    labels:
      __path__: /tmp/log/diffs.log
  pipeline_stages:
  - json:
      expressions:
        diff:
        file:
        snapshot:
